[tool.poetry]
name = "repl_python3_computations-32"
version = "0.1.0"
description = ""
authors = ["rhohloy <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^6.2.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
